# Generated by Django 4.1.2 on 2022-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], default='Pending', max_length=10),
        ),
    ]
