# Generated by Django 4.1.2 on 2022-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_customer_file_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Read', 'Read')], default='Pending', max_length=10),
        ),
    ]
